<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FarlaTweaks</RootNamespace>
    <AssemblyName>FarlaTweaks</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FarlaTweaks.Core\FarlaTweaks.Core.csproj" />
    <None Include="..\..\database\starter\tweaks.json" Link="database\starter\tweaks.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
